MODALS = [
    "adotarão",
    "cabe ",
    "caberá",
    "cabendo",
    "Compete à",
    "comunicará",
    "comunicarão",
    "deve",
    "devem ",
    "deverá",
    "deverão",
    "devendo",
    "definirá",
    "disciplinará",
    "disponibilizará",
    "disporá",
    "é obrigação do",
    "estabelecerá",
    "exercerá",
    "ficam sujeitos a",
    "fomentará",
    "implementará",
    "informarão",
    "inverterá o ônus da prova",
    "manterá",
    "observarão",
    "permanece sujeita a",
    "permanecem sujeitos a",
    "regulamentará",
    "regulamentarão",
    "São vedados",
    "será fornecida",
    "será fornecido",
    "serão públicas",
    "terá",
    "verificará"
]


CHAR_MATCH = {
    'á': 'a',
    'à': 'a',
    'ã': 'a',
    'â': 'a',
    'Á': 'A',
    'À': 'A',
    'Ã': 'A',
    'Â': 'A',
    
    'ç': 'c',
    'Ç': 'C',

    'é': 'e',
    'ê': 'e',
    'ẽ': 'e',
    'Ê': 'E',
    'Ẽ': 'E',
    'É': "E",
    'É': 'E',

    'í': 'i',
    'Í': 'I',
    
    'ó': 'o',
    'õ': 'o',
    'ô': 'o',
    'Ó': 'O',
    'Õ': 'O',
    'Ô': 'O',

    'ú': 'u',
    'ü': 'u',
    'Ú': 'U',
    'Ü': 'U',
    
    'º': 'o',
    '°': 'o',
    'ª': 'a',
    '§': '>',
    '\u201c': '',
    '\u2013': '-',
    '\u2212': '-',
    '”': '',
}